version: '3.6'

services:
  arangodb:
    networks:
       front:
          ipv4_address: 172.16.238.9    
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

  apiexample:
    networks:
       front:
          ipv4_address: 172.16.238.10    
    build: .
    command: node app.js
    ports:
    - "5000:5000"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
    - arangodb

  locustio:
    networks:
       front:
          ipv4_address: 172.16.238.11    
    image: locustio/locust    
    ports:
    - "8089:8089"
    volumes:
    - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py
    depends_on:
    - arangodb
    - apiexample


volumes:
  arangodb_data_container:
  arangodb_apps_data_container:

networks:
  front:
   external: true
